- name: vars from vars-file
  hosts: web
  vars_files:
  - 06-vars.yaml
  tasks: 
  - name: print the course information
    ansible.builtin.debug:
      msg: "Course:{{COURSE}},Trainer:{{TRAINER}},Duration: {{DURATION}}"

