- name: variables to print
  hosts: web
  vars:
   COURSE: "DevOps with AWS"
   TRAINER: "Sivakumar reddy"
   DURATION: "120Hrs"

  # vars_prompt: # This is the play level for all tasks
  # - name: COURSE
  #   prompt: Enter course name
  #   private: false # if not confidential
  # - name: TRAINER
  #   prompt: Enter trainer name
  # - name: DURATION
  #   prompt: Enter duration
  vars_files: # printing variables from vars_files
    - 06-vars.yaml
  tasks: 
  - name: print the course information
    ansible.builtin.debug:
      msg: "Course:{{COURSE}}"
  
  - name: vars from inventory
    ansible.builtin.debug:
      msg: "Course: {{COURSE}}"
 
  - name: print the inforamtion from play level variables
    ansible.builtin.debug:
      msg: "Hi, iam learning {{COURSE}}"

# 1. command line/arg
# 2. Task level
# 3. Files
# 4. Prompt
# 5. Play
# 6. inventory
# 7. Roles
