- name: create user
  hosts: web
  connection: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"  
