# here some install and some remove
- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ with_item.name}}"
      state: "{{ with_item.state }}"
    loop:
    - {{ name: 'mysql', state: 'present'}}
    - {{ name: 'nginx', state: 'absent'}}
    - {{ name: 'postfix', state: 'present'}}
    - {{ name: 'httpd', state: 'absent'}}
   