- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: Execute the command
    ansible.builtin.shell: ls -l > /tmp/output.text
    #ansible.builtin.command: ls -l > /tmp/output.text
