- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars: 
    subnet_id: subnet-0efdba4468fb44346
    sg_id: "sg-0fca81b9a3ae26a65"
    ami_id: "ami-0220d79f3f480ecf5"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the oputput
    ansible.builtin.debug:
     msg: "{{ ec2_instances }}"