- name: create a instances
  hosts: local
  connection: local
  vars: 
    subnet_id: "subnet-0efdba4468fb44346"
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-0fca81b9a3ae26a65"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      mame: "{{ item }}"
      vpc_subnet_id: "{{ subent_id }}"
      instance_type: t3.micro
      image_id: "{{ ami_id }}"
      security_group_id: "{{ sg_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the oputput
    ansible.builtin.debug:
     msg: "{{ ec2_instances }}"